apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopverse-frontend
  namespace: workshop
  labels:
    role: shopverse-frontend

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: shopverse-frontend
  template:
    metadata:
      labels:
        role: shopverse-frontend
    spec:
      containers:
      - name: frontend
        image: nishantbadhiye07/shopverse-frontend:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80
